export enum SITE_ROUTES {
    LOGIN = '/auth/login',
    REGISTER = '/auth/register',
    FORGET_PASSWORD = '/auth/forget-password',
    RESET_PASSWORD = '/auth/reset-password',
    VERIFY_OTP = '/auth/verify-otp',
    DASHBOARD = '/app/dashboard',
    INVENTORY_LISTING = '/app/inventory',
    INVENTORY_DETAIL = '/app/inventory/detail',
    INVENTORY_REORDER = '/app/inventory/reorder',
    JOBS_LISTING = '/app/jobs',
    USERS_LISTING = '/app/users',
    EQUIPMENTS_LISTING = '/app/equipments',
    EQUIPMENT_REQUESTS_LISTING = '/app/equipment-requests',
    EQUIPMENT_DETAIL = '/app/equipments/detail',
    REPORTS = '/app/reports',
    JOB_DETAIL = '/app/jobs/detail',
    SUBSCRIPTIONS_LISTING = '/subscriptions',
    CREATE_ROLE = '/app/users/create-role',
    WAREHOUSES_LISTING = '/app/warehouses',
    USER_DETAIL = '/app/users/detail',
    SETTINGS = '/app/settings',
    JOB_ACTIVITIES = '/app/jobs/detail/activities',
    JOB_INVENTORY_DETAIL = '/app/jobs/detail/activities/inventory-detail'
}