import { Injectable } from '@angular/core';

export interface ICountry {
  name: string;
  code: string;
}

export interface ICity {
  name: string;
  countryCode: string;
}

@Injectable({
  providedIn: 'root',
})
export class CountryCityService {
  private countries: ICountry[] = [
    { name: 'Afghanistan', code: 'AF' },
    { name: 'Albania', code: 'AL' },
    { name: 'Algeria', code: 'DZ' },
    { name: 'Andorra', code: 'AD' },
    { name: 'Angola', code: 'AO' },
    { name: 'Antigua and Barbuda', code: 'AG' },
    { name: 'Argentina', code: 'AR' },
    { name: 'Armenia', code: 'AM' },
    { name: 'Australia', code: 'AU' },
    { name: 'Austria', code: 'AT' },
    { name: 'Azerbaijan', code: 'AZ' },
    { name: 'Bahamas', code: 'BS' },
    { name: 'Bahrain', code: 'BH' },
    { name: 'Bangladesh', code: 'BD' },
    { name: 'Barbados', code: 'BB' },
    { name: 'Belarus', code: 'BY' },
    { name: 'Belgium', code: 'BE' },
    { name: 'Belize', code: 'BZ' },
    { name: 'Benin', code: 'BJ' },
    { name: 'Bhutan', code: 'BT' },
    { name: 'Bolivia', code: 'BO' },
    { name: 'Bosnia and Herzegovina', code: 'BA' },
    { name: 'Botswana', code: 'BW' },
    { name: 'Brazil', code: 'BR' },
    { name: 'Brunei', code: 'BN' },
    { name: 'Bulgaria', code: 'BG' },
    { name: 'Burkina Faso', code: 'BF' },
    { name: 'Burundi', code: 'BI' },
    { name: 'Cabo Verde', code: 'CV' },
    { name: 'Cambodia', code: 'KH' },
    { name: 'Cameroon', code: 'CM' },
    { name: 'Canada', code: 'CA' },
    { name: 'Central African Republic', code: 'CF' },
    { name: 'Chad', code: 'TD' },
    { name: 'Chile', code: 'CL' },
    { name: 'China', code: 'CN' },
    { name: 'Colombia', code: 'CO' },
    { name: 'Comoros', code: 'KM' },
    { name: 'Congo (DRC)', code: 'CD' },
    { name: 'Congo (Republic)', code: 'CG' },
    { name: 'Costa Rica', code: 'CR' },
    { name: 'Croatia', code: 'HR' },
    { name: 'Cuba', code: 'CU' },
    { name: 'Cyprus', code: 'CY' },
    { name: 'Czech Republic', code: 'CZ' },
    { name: 'Denmark', code: 'DK' },
    { name: 'Djibouti', code: 'DJ' },
    { name: 'Dominican Republic', code: 'DO' },
    { name: 'Ecuador', code: 'EC' },
    { name: 'Egypt', code: 'EG' },
    { name: 'El Salvador', code: 'SV' },
    { name: 'Equatorial Guinea', code: 'GQ' },
    { name: 'Eritrea', code: 'ER' },
    { name: 'Estonia', code: 'EE' },
    { name: 'Eswatini', code: 'SZ' },
    { name: 'Ethiopia', code: 'ET' },
    { name: 'Fiji', code: 'FJ' },
    { name: 'Finland', code: 'FI' },
    { name: 'France', code: 'FR' },
    { name: 'Gabon', code: 'GA' },
    { name: 'Gambia', code: 'GM' },
    { name: 'Georgia', code: 'GE' },
    { name: 'Germany', code: 'DE' },
    { name: 'Ghana', code: 'GH' },
    { name: 'Greece', code: 'GR' },
    { name: 'Guatemala', code: 'GT' },
    { name: 'Guinea', code: 'GN' },
    { name: 'Guinea-Bissau', code: 'GW' },
    { name: 'Guyana', code: 'GY' },
    { name: 'Haiti', code: 'HT' },
    { name: 'Honduras', code: 'HN' },
    { name: 'Hungary', code: 'HU' },
    { name: 'Iceland', code: 'IS' },
    { name: 'India', code: 'IN' },
    { name: 'Indonesia', code: 'ID' },
    { name: 'Iran', code: 'IR' },
    { name: 'Iraq', code: 'IQ' },
    { name: 'Ireland', code: 'IE' },
    { name: 'Israel', code: 'IL' },
    { name: 'Italy', code: 'IT' },
    { name: 'Ivory Coast', code: 'CI' },
    { name: 'Jamaica', code: 'JM' },
    { name: 'Japan', code: 'JP' },
    { name: 'Jordan', code: 'JO' },
    { name: 'Kazakhstan', code: 'KZ' },
    { name: 'Kenya', code: 'KE' },
    { name: 'Kuwait', code: 'KW' },
    { name: 'Kyrgyzstan', code: 'KG' },
    { name: 'Laos', code: 'LA' },
    { name: 'Latvia', code: 'LV' },
    { name: 'Lebanon', code: 'LB' },
    { name: 'Lesotho', code: 'LS' },
    { name: 'Liberia', code: 'LR' },
    { name: 'Libya', code: 'LY' },
    { name: 'Liechtenstein', code: 'LI' },
    { name: 'Lithuania', code: 'LT' },
    { name: 'Luxembourg', code: 'LU' },
    { name: 'Madagascar', code: 'MG' },
    { name: 'Malawi', code: 'MW' },
    { name: 'Malaysia', code: 'MY' },
    { name: 'Maldives', code: 'MV' },
    { name: 'Mali', code: 'ML' },
    { name: 'Malta', code: 'MT' },
    { name: 'Mauritania', code: 'MR' },
    { name: 'Mauritius', code: 'MU' },
    { name: 'Mexico', code: 'MX' },
    { name: 'Moldova', code: 'MD' },
    { name: 'Monaco', code: 'MC' },
    { name: 'Mongolia', code: 'MN' },
    { name: 'Montenegro', code: 'ME' },
    { name: 'Morocco', code: 'MA' },
    { name: 'Mozambique', code: 'MZ' },
    { name: 'Myanmar', code: 'MM' },
    { name: 'Namibia', code: 'NA' },
    { name: 'Nepal', code: 'NP' },
    { name: 'Netherlands', code: 'NL' },
    { name: 'New Zealand', code: 'NZ' },
    { name: 'Nicaragua', code: 'NI' },
    { name: 'Niger', code: 'NE' },
    { name: 'Nigeria', code: 'NG' },
    { name: 'North Korea', code: 'KP' },
    { name: 'North Macedonia', code: 'MK' },
    { name: 'Norway', code: 'NO' },
    { name: 'Oman', code: 'OM' },
    { name: 'Pakistan', code: 'PK' },
    { name: 'Palestine', code: 'PS' },
    { name: 'Panama', code: 'PA' },
    { name: 'Papua New Guinea', code: 'PG' },
    { name: 'Paraguay', code: 'PY' },
    { name: 'Peru', code: 'PE' },
    { name: 'Philippines', code: 'PH' },
    { name: 'Poland', code: 'PL' },
    { name: 'Portugal', code: 'PT' },
    { name: 'Qatar', code: 'QA' },
    { name: 'Romania', code: 'RO' },
    { name: 'Russia', code: 'RU' },
    { name: 'Rwanda', code: 'RW' },
    { name: 'San Marino', code: 'SM' },
    { name: 'Saudi Arabia', code: 'SA' },
    { name: 'Senegal', code: 'SN' },
    { name: 'Serbia', code: 'RS' },
    { name: 'Sierra Leone', code: 'SL' },
    { name: 'Singapore', code: 'SG' },
    { name: 'Slovakia', code: 'SK' },
    { name: 'Slovenia', code: 'SI' },
    { name: 'Somalia', code: 'SO' },
    { name: 'South Africa', code: 'ZA' },
    { name: 'South Korea', code: 'KR' },
    { name: 'South Sudan', code: 'SS' },
    { name: 'Spain', code: 'ES' },
    { name: 'Sri Lanka', code: 'LK' },
    { name: 'Sudan', code: 'SD' },
    { name: 'Suriname', code: 'SR' },
    { name: 'Sweden', code: 'SE' },
    { name: 'Switzerland', code: 'CH' },
    { name: 'Syria', code: 'SY' },
    { name: 'Taiwan', code: 'TW' },
    { name: 'Tajikistan', code: 'TJ' },
    { name: 'Tanzania', code: 'TZ' },
    { name: 'Thailand', code: 'TH' },
    { name: 'Timor-Leste', code: 'TL' },
    { name: 'Togo', code: 'TG' },
    { name: 'Trinidad and Tobago', code: 'TT' },
    { name: 'Tunisia', code: 'TN' },
    { name: 'Turkey', code: 'TR' },
    { name: 'Turkmenistan', code: 'TM' },
    { name: 'Uganda', code: 'UG' },
    { name: 'Ukraine', code: 'UA' },
    { name: 'United Arab Emirates', code: 'AE' },
    { name: 'United Kingdom', code: 'GB' },
    { name: 'United States', code: 'US' },
    { name: 'Uruguay', code: 'UY' },
    { name: 'Uzbekistan', code: 'UZ' },
    { name: 'Venezuela', code: 'VE' },
    { name: 'Vietnam', code: 'VN' },
    { name: 'Yemen', code: 'YE' },
    { name: 'Zambia', code: 'ZM' },
    { name: 'Zimbabwe', code: 'ZW' },
  ];

  private citiesByCountry: { [countryCode: string]: string[] } = {
    AF: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad'],
    AL: ['Tirana', 'Durrës', 'Vlorë', 'Shkodër', 'Fier'],
    DZ: ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida'],
    AD: ['Andorra la Vella', 'Escaldes-Engordany', 'Encamp', 'La Massana', 'Sant Julià de Lòria'],
    AO: ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Kuito'],
    AG: ["Saint John's", 'All Saints', 'Liberta', "Potter's Village", 'Bolans'],
    AR: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'Tucumán', 'Mar del Plata'],
    AM: ['Yerevan', 'Gyumri', 'Vanadzor', 'Vagharshapat', 'Abovyan'],
    AU: [
      'Sydney',
      'Melbourne',
      'Brisbane',
      'Perth',
      'Adelaide',
      'Canberra',
      'Gold Coast',
      'Darwin',
    ],
    AT: ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt'],
    AZ: ['Baku', 'Ganja', 'Sumqayit', 'Mingachevir', 'Nakhchivan'],
    BS: ['Nassau', 'Freeport', 'West End', 'Coopers Town', 'Marsh Harbour'],
    BH: ['Manama', 'Riffa', 'Muharraq', 'Hamad Town', 'Isa Town'],
    BD: ['Dhaka', 'Chittagong', 'Sylhet', 'Khulna', 'Rajshahi', 'Comilla', 'Mymensingh'],
    BB: ['Bridgetown', 'Speightstown', 'Oistins', 'Bathsheba', 'Holetown'],
    BY: ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk', 'Grodno', 'Brest'],
    BE: ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège', 'Bruges'],
    BZ: ['Belmopan', 'Belize City', 'San Ignacio', 'Orange Walk', 'Dangriga'],
    BJ: ['Cotonou', 'Porto-Novo', 'Parakou', 'Djougou', 'Bohicon'],
    BT: ['Thimphu', 'Phuntsholing', 'Paro', 'Punakha', 'Wangdue Phodrang'],
    BO: ['Sucre', 'La Paz', 'Santa Cruz', 'Cochabamba', 'Oruro', 'Potosí'],
    BA: ['Sarajevo', 'Banja Luka', 'Tuzla', 'Zenica', 'Mostar'],
    BW: ['Gaborone', 'Francistown', 'Molepolole', 'Serowe', 'Maun'],
    BR: [
      'São Paulo',
      'Rio de Janeiro',
      'Brasília',
      'Salvador',
      'Fortaleza',
      'Belo Horizonte',
      'Manaus',
      'Curitiba',
      'Recife',
    ],
    BN: ['Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Tutong', 'Bangar'],
    BG: ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse', 'Stara Zagora'],
    BF: ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Banfora', 'Ouahigouya'],
    BI: ['Gitega', 'Bujumbura', 'Muyinga', 'Ruyigi', 'Ngozi'],
    CV: ['Praia', 'Mindelo', 'Santa Maria', 'Assomada', 'Pedra Badejo'],
    KH: ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville', 'Kampong Cham'],
    CM: ['Yaoundé', 'Douala', 'Garoua', 'Bamenda', 'Maroua'],
    CA: [
      'Toronto',
      'Montreal',
      'Vancouver',
      'Calgary',
      'Edmonton',
      'Ottawa',
      'Winnipeg',
      'Quebec City',
      'Halifax',
    ],
    CF: ['Bangui', 'Bimbo', 'Mbaïki', 'Berberati', 'Kaga-Bandoro'],
    TD: ["N'Djamena", 'Moundou', 'Sarh', 'Abéché', 'Kélo'],
    CL: ['Santiago', 'Valparaíso', 'Concepción', 'Antofagasta', 'Viña del Mar', 'Temuco'],
    CN: [
      'Beijing',
      'Shanghai',
      'Guangzhou',
      'Shenzhen',
      'Chengdu',
      'Wuhan',
      "Xi'an",
      'Hangzhou',
      'Nanjing',
      'Tianjin',
    ],
    CO: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Cúcuta', 'Bucaramanga'],
    KM: ['Moroni', 'Mutsamudu', 'Fomboni', 'Domoni', 'Tsimbeo'],
    CD: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kisangani', 'Bukavu'],
    CG: ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi', 'Impfondo'],
    CR: ['San José', 'Cartago', 'Alajuela', 'Heredia', 'Liberia'],
    HR: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Dubrovnik'],
    CU: ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Guantánamo'],
    CY: ['Nicosia', 'Limassol', 'Larnaca', 'Paphos', 'Famagusta'],
    CZ: ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec', 'Olomouc'],
    DK: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg'],
    DJ: ['Djibouti City', 'Ali Sabieh', 'Dikhil', 'Tadjourah', 'Obock'],
    DO: [
      'Santo Domingo',
      'Santiago',
      'San Pedro de Macorís',
      'La Romana',
      'San Francisco de Macorís',
    ],
    EC: ['Quito', 'Guayaquil', 'Cuenca', 'Ambato', 'Manta'],
    EG: ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said', 'Luxor', 'Aswan'],
    SV: ['San Salvador', 'Santa Ana', 'San Miguel', 'Mejicanos', 'Soyapango'],
    GQ: ['Malabo', 'Bata', 'Ebebiyin', 'Aconibe', 'Añisoc'],
    ER: ['Asmara', 'Keren', 'Massawa', 'Assab', 'Mendefera'],
    EE: ['Tallinn', 'Tartu', 'Narva', 'Pärnu', 'Kohtla-Järve'],
    SZ: ['Mbabane', 'Manzini', 'Lobamba', 'Big Bend', 'Mankayane'],
    ET: ['Addis Ababa', 'Dire Dawa', "Mek'ele", 'Gondar', 'Hawassa', 'Bahir Dar'],
    FJ: ['Suva', 'Lautoka', 'Nadi', 'Labasa', 'Ba'],
    FI: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku'],
    FR: [
      'Paris',
      'Marseille',
      'Lyon',
      'Toulouse',
      'Nice',
      'Nantes',
      'Strasbourg',
      'Bordeaux',
      'Lille',
    ],
    GA: ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem', 'Moanda'],
    GM: ['Banjul', 'Serekunda', 'Brikama', 'Bakau', 'Farafenni'],
    GE: ['Tbilisi', 'Kutaisi', 'Batumi', 'Rustavi', 'Zugdidi'],
    DE: [
      'Berlin',
      'Hamburg',
      'Munich',
      'Cologne',
      'Frankfurt',
      'Stuttgart',
      'Düsseldorf',
      'Dortmund',
      'Leipzig',
    ],
    GH: ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi', 'Ashaiman'],
    GR: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa', 'Rhodes'],
    GT: ['Guatemala City', 'Mixco', 'Villa Nueva', 'Quetzaltenango', 'Huehuetenango'],
    GN: ['Conakry', 'Nzérékoré', 'Kindia', 'Kankan', 'Labé'],
    GW: ['Bissau', 'Bafatá', 'Gabú', 'Bissorã', 'Bolama'],
    GY: ['Georgetown', 'Linden', 'New Amsterdam', 'Anna Regina', 'Bartica'],
    HT: ['Port-au-Prince', 'Carrefour', 'Delmas', 'Pétionville', 'Cap-Haïtien'],
    HN: ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba', 'El Progreso'],
    HU: ['Budapest', 'Debrecen', 'Miskolc', 'Szeged', 'Pécs', 'Győr'],
    IS: ['Reykjavik', 'Kópavogur', 'Hafnarfjörður', 'Akureyri', 'Reykjanesbær'],
    IN: [
      'Mumbai',
      'Delhi',
      'Bangalore',
      'Hyderabad',
      'Chennai',
      'Kolkata',
      'Ahmedabad',
      'Pune',
      'Jaipur',
      'Lucknow',
      'Surat',
      'Kanpur',
    ],
    ID: [
      'Jakarta',
      'Surabaya',
      'Bandung',
      'Bekasi',
      'Medan',
      'Tangerang',
      'Depok',
      'Semarang',
      'Makassar',
      'Palembang',
    ],
    IR: ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Tabriz', 'Shiraz'],
    IQ: ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Najaf', 'Kirkuk'],
    IE: ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford'],
    IL: ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion', 'Petah Tikva', 'Beersheba'],
    IT: ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Venice'],
    CI: ['Abidjan', 'Bouaké', 'Daloa', 'Korhogo', 'Yamoussoukro'],
    JM: ['Kingston', 'Spanish Town', 'Portmore', 'Montego Bay', 'May Pen'],
    JP: [
      'Tokyo',
      'Osaka',
      'Nagoya',
      'Yokohama',
      'Sapporo',
      'Kobe',
      'Kyoto',
      'Fukuoka',
      'Kawasaki',
      'Hiroshima',
    ],
    JO: ['Amman', 'Zarqa', 'Irbid', 'Russeifa', 'Wadi as-Seer'],
    KZ: ['Nur-Sultan', 'Almaty', 'Shymkent', 'Karaganda', 'Aktobe'],
    KE: ['Nairobi', 'Mombasa', 'Nakuru', 'Kisumu', 'Ruiru', 'Eldoret'],
    KW: ['Kuwait City', 'Salmiya', 'Hawalli', 'Al Ahmadi', 'Abraq Khaytan'],
    KG: ['Bishkek', 'Osh', 'Jalal-Abad', 'Karakol', 'Tokmok'],
    LA: ['Vientiane', 'Pakse', 'Savannakhet', 'Luang Prabang', 'Thakhek'],
    LV: ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Jūrmala'],
    LB: ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Jounieh'],
    LS: ['Maseru', 'Teyateyaneng', 'Mafeteng', 'Hlotse', "Mohale's Hoek"],
    LR: ['Monrovia', 'Gbarnga', 'Kakata', 'Bensonville', 'Harper'],
    LY: ['Tripoli', 'Benghazi', 'Misrata', 'Tarhuna', 'Bayda'],
    LI: ['Vaduz', 'Schaan', 'Balzers', 'Triesen', 'Eschen'],
    LT: ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys'],
    LU: ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange', 'Dudelange', 'Ettelbruck'],
    MG: ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa', 'Mahajanga'],
    MW: ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba', 'Kasungu'],
    MY: [
      'Kuala Lumpur',
      'Johor Bahru',
      'Ipoh',
      'Petaling Jaya',
      'Shah Alam',
      'Penang',
      'Kota Kinabalu',
    ],
    MV: ['Malé', 'Addu City', 'Fuvahmulah', 'Kulhudhuffushi', 'Thinadhoo'],
    ML: ['Bamako', 'Sikasso', 'Mopti', 'Koutiala', 'Ségou'],
    MT: ['Valletta', 'Birkirkara', 'Qormi', 'Mosta', 'Żabbar'],
    MR: ['Nouakchott', 'Nouadhibou', 'Kiffa', 'Rosso', 'Kaédi'],
    MU: ['Port Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix', 'Curepipe', 'Quatre Bornes'],
    MX: [
      'Mexico City',
      'Guadalajara',
      'Monterrey',
      'Puebla',
      'Tijuana',
      'León',
      'Juárez',
      'Zapopan',
      'Mérida',
    ],
    MD: ['Chișinău', 'Tiraspol', 'Bălți', 'Bender', 'Rîbnița'],
    MC: ['Monaco', 'Monte Carlo', 'La Condamine', 'Fontvieille', 'Moneghetti'],
    MN: ['Ulaanbaatar', 'Erdenet', 'Darkhan', 'Choibalsan', 'Ölgii'],
    ME: ['Podgorica', 'Nikšić', 'Herceg Novi', 'Pljevlja', 'Bijelo Polje'],
    MA: ['Casablanca', 'Rabat', 'Fes', 'Marrakech', 'Agadir', 'Tangier', 'Meknes'],
    MZ: ['Maputo', 'Matola', 'Nampula', 'Beira', 'Quelimane'],
    MM: ['Naypyidaw', 'Yangon', 'Mandalay', 'Mawlamyine', 'Bago'],
    NA: ['Windhoek', 'Rundu', 'Walvis Bay', 'Swakopmund', 'Oshakati'],
    NP: ['Kathmandu', 'Pokhara', 'Lalitpur', 'Bharatpur', 'Biratnagar'],
    NL: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Tilburg', 'Groningen'],
    NZ: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Dunedin'],
    NI: ['Managua', 'León', 'Masaya', 'Chinandega', 'Matagalpa'],
    NE: ['Niamey', 'Zinder', 'Maradi', 'Agadez', 'Tahoua'],
    NG: ['Lagos', 'Kano', 'Ibadan', 'Abuja', 'Port Harcourt', 'Benin City', 'Kaduna', 'Enugu'],
    KP: ['Pyongyang', 'Hamhung', 'Chongjin', 'Nampo', 'Wonsan'],
    MK: ['Skopje', 'Bitola', 'Kumanovo', 'Prilep', 'Tetovo'],
    NO: ['Oslo', 'Bergen', 'Stavanger', 'Trondheim', 'Tromsø'],
    OM: ['Muscat', 'Seeb', 'Salalah', 'Bawshar', 'Sohar'],
    PK: [
      'Karachi',
      'Lahore',
      'Faisalabad',
      'Rawalpindi',
      'Islamabad',
      'Gujranwala',
      'Peshawar',
      'Multan',
      'Quetta',
    ],
    PS: ['Gaza', 'Ramallah', 'Nablus', 'Hebron', 'Jenin'],
    PA: ['Panama City', 'San Miguelito', 'Tocumen', 'David', 'La Chorrera'],
    PG: ['Port Moresby', 'Lae', 'Arawa', 'Mount Hagen', 'Madang'],
    PY: ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Capiatá'],
    PE: ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Iquitos', 'Cusco'],
    PH: ['Manila', 'Quezon City', 'Davao', 'Caloocan', 'Cebu City', 'Zamboanga', 'Antipolo'],
    PL: ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Katowice'],
    PT: ['Lisbon', 'Porto', 'Amadora', 'Braga', 'Setúbal', 'Coimbra'],
    QA: ['Doha', 'Al Rayyan', 'Umm Salal', 'Al Wakrah', 'Al Khor'],
    RO: ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova'],
    RU: [
      'Moscow',
      'Saint Petersburg',
      'Novosibirsk',
      'Yekaterinburg',
      'Kazan',
      'Nizhny Novgorod',
      'Chelyabinsk',
      'Omsk',
      'Samara',
    ],
    RW: ['Kigali', 'Butare', 'Gitarama', 'Musanze', 'Byumba'],
    SM: ['San Marino', 'Serravalle', 'Fiorentino', 'Borgo Maggiore', 'Acquaviva'],
    SA: ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Tabuk'],
    SN: ['Dakar', 'Touba', 'Thiès', 'Kaolack', "M'Bour"],
    RS: ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica'],
    SL: ['Freetown', 'Bo', 'Kenema', 'Makeni', 'Koidu'],
    SG: ['Singapore', 'Jurong East', 'Woodlands', 'Tampines', 'Ang Mo Kio'],
    SK: ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Banská Bystrica'],
    SI: ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Koper'],
    SO: ['Mogadishu', 'Hargeisa', 'Berbera', 'Kismayo', 'Marka'],
    ZA: [
      'Johannesburg',
      'Cape Town',
      'Durban',
      'Pretoria',
      'Port Elizabeth',
      'Bloemfontein',
      'Soweto',
    ],
    KR: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon'],
    SS: ['Juba', 'Wau', 'Malakal', 'Aweil', 'Yei'],
    ES: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Bilbao'],
    LK: ['Colombo', 'Dehiwala', 'Moratuwa', 'Jaffna', 'Kandy'],
    SD: ['Khartoum', 'Omdurman', 'Port Sudan', 'Kassala', 'El Obeid'],
    SR: ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie', 'Moengo', 'Nieuw Amsterdam'],
    SE: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås', 'Örebro'],
    CH: ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne', 'Winterthur'],
    SY: ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama'],
    TW: ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Hsinchu', 'Keelung'],
    TJ: ['Dushanbe', 'Khujand', 'Kulob', 'Bokhtar', 'Istaravshan'],
    TZ: ['Dar es Salaam', 'Mwanza', 'Arusha', 'Dodoma', 'Mbeya', 'Zanzibar City'],
    TH: ['Bangkok', 'Nonthaburi', 'Pak Kret', 'Hat Yai', 'Chiang Mai', 'Phuket'],
    TL: ['Dili', 'Baucau', 'Maliana', 'Suai', 'Liquiçá'],
    TG: ['Lomé', 'Sokodé', 'Kara', 'Atakpamé', 'Kpalimé'],
    TT: ['Port of Spain', 'Chaguanas', 'San Fernando', 'Arima', 'Point Fortin'],
    TN: ['Tunis', 'Sfax', 'Sousse', 'Ettadhamen', 'Kairouan'],
    TR: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Adana', 'Gaziantep', 'Konya', 'Antalya'],
    TM: ['Ashgabat', 'Türkmenabat', 'Daşoguz', 'Mary', 'Balkanabat'],
    UG: ['Kampala', 'Gulu', 'Lira', 'Mbarara', 'Jinja'],
    UA: ['Kyiv', 'Kharkiv', 'Odessa', 'Dnipro', 'Donetsk', 'Zaporizhzhia', 'Lviv'],
    AE: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman', 'Ras Al Khaimah'],
    GB: [
      'London',
      'Birmingham',
      'Manchester',
      'Leeds',
      'Glasgow',
      'Liverpool',
      'Edinburgh',
      'Bristol',
      'Cardiff',
    ],
    US: [
      'New York',
      'Los Angeles',
      'Chicago',
      'Houston',
      'Phoenix',
      'Philadelphia',
      'San Antonio',
      'San Diego',
      'Dallas',
      'San Jose',
      'Austin',
      'Jacksonville',
      'Seattle',
      'Denver',
      'Washington D.C.',
      'Nashville',
      'Boston',
      'Las Vegas',
      'Miami',
      'Atlanta',
    ],
    UY: ['Montevideo', 'Salto', 'Paysandú', 'Las Piedras', 'Rivera'],
    UZ: ['Tashkent', 'Namangan', 'Samarkand', 'Andijan', 'Nukus'],
    VE: ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay'],
    VN: ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Hai Phong', 'Can Tho', 'Bien Hoa'],
    YE: ['Sanaa', 'Aden', 'Taiz', 'Al Hudaydah', 'Ibb'],
    ZM: ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe', 'Chingola'],
    ZW: ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Gweru'],
  };
  getCountries(): ICountry[] {
    return this.countries;
  }
  getCitiesByCountryCode(countryCode: string): string[] {
    return this.citiesByCountry[countryCode] ?? [];
  }
  getCitiesByCountryName(countryName: string): string[] {
    const country = this.countries.find((c) => c.name.toLowerCase() === countryName.toLowerCase());
    if (!country) return [];
    return this.citiesByCountry[country.code] ?? [];
  }
}
